# Generated by Django 4.2.1 on 2023-05-17 05:21

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone
import redbusapps.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100, verbose_name='Bus_Name')),
                ('bus_number', models.IntegerField(verbose_name='Bus_Number')),
                ('start_point', models.CharField(max_length=100, verbose_name='start_point')),
                ('destination', models.CharField(max_length=100, verbose_name='destination')),
                ('arrival_time', models.DateTimeField(verbose_name='Arrival_Time')),
                ('departure_time', models.DateTimeField(verbose_name='Departure_Time')),
                ('bus_image', cloudinary.models.CloudinaryField(max_length=255)),
            ],
            options={
                'db_table': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('phone_number', models.CharField(max_length=10, unique=True, verbose_name='phone_number')),
                ('user_bio', models.CharField(max_length=100, verbose_name='user_bio')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'CustomUser',
            },
            managers=[
                ('objects', redbusapps.manager.UserManager()),
            ],
        ),
    ]
